import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const release = { status: 'comingSoon', version: null, releaseDate: null, apkUrl: null, apkSize: null, minimumAndroidVersion: null, releaseNotes: [] };
const features = [
  ['Business overview', 'See Billed, Received, Outstanding, Invoices, Overdue and collection rate for the active business.'],
  ['Customers', 'Add customers, keep their information organized and review customer dues.'],
  ['Billing & invoices', 'Create invoices with line items, payments and customer billing information.'],
  ['Payments', 'Record received payments and keep outstanding invoice amounts up to date.'],
  ['Income & expenses', 'Review customer payments and owner income alongside business expenses.'],
  ['Inventory', 'Keep inventory products available for the business workflows that use them.'],
  ['Business management', 'Manage business information and upload a UPI Payment QR Code for invoices.'],
  ['App Lock', 'Protect the app with a secure PIN and optional biometric unlock.'],
  ['Offline & sync', 'Keep business data available offline and synchronize supported records when connected.']
];
const nav = [['Home','/'],['Features','/features'],['Download','/download'],["What's New",'/whats-new'],['Help','/help'],['About','/about']];
const Icon = ({type='spark'}) => <svg viewBox="0 0 24 24" aria-hidden="true"><path d={type==='menu'?'M4 7h16M4 12h16M4 17h16':type==='arrow'?'M5 12h14m-6-6 6 6-6 6':type==='download'?'M12 3v11m0 0 4-4m-4 4-4-4M5 21h14':type==='close'?'M6 6l12 12M18 6 6 18':'M12 3 14.4 9.6 21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4L12 3'} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>;
function Brand(){return <a className="brand" href="/" aria-label="OneBill home"><img src="/assets/onebill-logo.png"/><span>OneBill</span></a>}
function Button({children, href, secondary=false}){return <a className={'button '+(secondary?'secondary':'')} href={href}>{children}</a>}
function Navbar(){const [open,setOpen]=useState(false); return <><header><div className="nav wrap"><Brand/><nav>{nav.map(([x,u])=><a key={u} href={u}>{x}</a>)}</nav><Button href="/download">Download <Icon type="arrow"/></Button><button className="menub" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}><Icon type={open?'close':'menu'}/></button></div></header>{open&&<div className="mobile-nav">{nav.map(([x,u])=><a key={u} href={u} onClick={()=>setOpen(false)}>{x}</a>)}<Button href="/download">Download OneBill</Button></div>}</>}
function Footer(){return <footer><div className="wrap foot"><div><Brand/><p>Simple billing for growing businesses.</p></div><div><b>Product</b><a href="/features">Features</a><a href="/download">Download</a><a href="/whats-new">What's New</a></div><div><b>Resources</b><a href="/help">Help</a><a href="/about">About</a><a href="/contact">Contact</a></div><div><b>Legal</b><a href="/privacy">Privacy Policy</a><a href="/terms">Terms</a></div></div><div className="wrap copyright">© 2026 OneBill. All rights reserved.</div></footer>}
function Phone({src,alt,large=false}){return <div className={'phone '+(large?'large':'')}><div className="phone-top"></div><img src={src} alt={alt}/></div>}
function Eyebrow({children}){return <div className="eyebrow"><i></i>{children}</div>}
function Home(){return <><section className="hero"><div className="wrap hero-grid"><div className="hero-copy"><Eyebrow>OneBill</Eyebrow><h1>Simple billing for <em>growing businesses.</em></h1><p>OneBill helps businesses manage billing, customers, payments, income and expenses in one simple Android app.</p><div className="actions"><Button href="/download">Download OneBill <Icon type="download"/></Button><Button secondary href="/features">Explore Features <Icon type="arrow"/></Button></div><div className="availability"><span>Android app</span><span>Google Play <small>Coming Soon</small></span></div></div><div className="hero-visual"><div className="orb"></div><div className="hero-panel"><span className="mini-icon"><Icon/></span><b>Business overview</b><p>Invoices · Customers · Income · Expenses</p><div><strong>Received</strong><small>Payments from customers</small></div><div><strong>Outstanding</strong><small>Invoices still due</small></div></div></div></div></section><section className="wrap section intro"><Eyebrow>Everything your business needs in one place</Eyebrow><h2>Stay on top of <em>everyday billing.</em></h2><div className="benefits">{[['01','Billing','Create and manage bills and invoices.'],['02','Customers','Keep customer information and dues organized.'],['03','Payments','Record received payments and track outstanding amounts.'],['04','Income & Expenses','Keep track of business money coming in and going out.']].map(x=><article key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="feature-band"><div className="wrap split"><div><Eyebrow>OneBill workflow</Eyebrow><h2>Run your business in <em>a few simple steps.</em></h2><p>Set up your business, add customers, create bills, record payments and keep your financial activity organized.</p><Button secondary href="/features">Explore Features <Icon type="arrow"/></Button></div><div className="feature-list">{[['01','Add your business','Business information stays available on your device.'],['02','Add customers and create bills','Keep customer dues and invoices together.'],['03','Record payments and track your business','Review income, expenses and outstanding amounts.']].map(([n,t,d])=><div key={n}><span className="num">{n}</span><div><h3>{t}</h3><p>{d}</p></div><Icon type="arrow"/></div>)}</div></div></section><section className="wrap section how"><Eyebrow>Available when you need it</Eyebrow><h2>Your business data stays <em>available offline.</em></h2><p className="section-lead">After setup, OneBill keeps your business information available on your device. When connectivity is available, supported business data can sync with your account.</p><CTA/></section></>}
function CTA(){return <section className="wrap"><div className="cta"><div><Eyebrow>Get started</Eyebrow><h2>Ready to simplify your billing?</h2><p>Download OneBill for Android and get started with a more focused business workflow.</p></div><Button href="/download">Get OneBill <Icon type="arrow"/></Button></div></section>}
function PageHead({eyebrow,title,children}){return <section className="page-head wrap"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1>{children&&<p>{children}</p>}</section>}
function Features(){return <><PageHead eyebrow="OneBill features" title={<>Everything you need for <em>everyday billing.</em></>}>Designed around the essential jobs of running and organizing your business.</PageHead><section className="wrap grid-features">{features.map(([t,d],i)=><article key={t}><span className="feature-symbol">0{i+1}</span><h2>{t}</h2><p>{d}</p><span className="line"></span></article>)}</section><CTA/></>}
function Download(){return <><PageHead eyebrow="Android download" title={<>Download <em>OneBill.</em></>}>Get the OneBill Android app and manage your business from your phone.</PageHead><section className="wrap download-grid"><div className="release-card"><span className="release-logo"><img src="/assets/onebill-logo.png"/></span><div className="release-top"><div><small>OneBill</small><h2>Android app</h2></div><span className="android">Coming soon</span></div><p className="release-note">We’re preparing the first public release of OneBill. Download details will appear here when the Android app is ready.</p><div className="button disabled" aria-disabled="true">Android app — Coming soon</div></div><aside className="install"><Eyebrow>When it’s available</Eyebrow><h2>OneBill on Android.</h2><p className="release-note">The release page will include the APK, version, release date and installation guidance when distribution begins.</p><div className="play">Google Play <span>Coming soon</span></div></aside></section></>}
const helpGroups=[['Dashboard',['Understanding Business overview','Reading billed, received and outstanding amounts','Reviewing overdue invoices and collection rate']],['Customers',['Adding a customer','Finding a customer','Checking a customer’s due amount']],['Invoices & payments',['Managing invoices','Recording received payments','Reviewing overdue payment status']],['Income & expenses',['Reviewing Income','Managing Expenses']],['Security & data',['Using App Lock','Working offline and syncing data','Deleting a business']]];
function Help(){const [active,setActive]=useState(null);const answers={'Understanding Business overview':'Business overview brings together Billed, Received, Outstanding, Invoices, Overdue and collection rate information for the active business.','Reading billed, received and outstanding amounts':'Billed is the invoice total, Received is recorded customer payment, and Outstanding is the amount still due.','Reviewing overdue invoices and collection rate':'The overview highlights overdue invoices and lets you open the overdue invoice review. Collection rate is calculated from received against billed.','Adding a customer':'Open Customers and select Add customer. Enter the customer details and save to add them to the active business.','Finding a customer':'Open Customers to see the customers belonging to the active business. Each customer entry shows the amount currently due when applicable.','Checking a customer’s due amount':'Select a customer from Customers to review their invoices and outstanding amount.','Managing invoices':'Invoices are created and managed for the active business and its customers. Invoice line items and payments are part of the invoice record.','Recording received payments':'Customer payments appear in Income as received payments and reduce the outstanding amount on the related invoice.','Reviewing overdue payment status':'Use the overdue invoices alert in Business overview to review invoices whose payment is still overdue.','Reviewing Income':'Income combines customer payments with owner income entries. Use the Income tab to review entries by month and source.','Managing Expenses':'Open Expenses to add, review and manage business expense entries for the active business.','Using App Lock':'App Lock can be configured with a secure 4–6 digit PIN and optional biometric unlock for returning to the app.','Working offline and syncing data':'Business information is saved locally so the app remains usable without internet. When connected, supported operations are synchronized and failed operations can be retried.','Deleting a business':'Business deletion is permanent. It removes invoices, customers, inventory, expenses and cloud sync records for that business. '};return <><PageHead eyebrow="Help center" title={<>How can we <em>help?</em></>}>Find your way around the OneBill app, from the business overview to customers, invoices, income and expenses.</PageHead><section className="wrap help-grid">{helpGroups.map(([g,qs])=><div className="faq-group" key={g}><h2>{g}</h2>{qs.map(q=><div className="faq" key={q}><button onClick={()=>setActive(active===q?null:q)} aria-expanded={active===q}>{q}<span>{active===q?'−':'+'}</span></button>{active===q&&<p>{answers[q]}</p>}</div>)}</div>)}</section><CTA/></>}
function WhatsNew(){return <><PageHead eyebrow="Release notes" title={<>What's <em>new.</em></>}>Updates to OneBill will be documented here as new releases become available.</PageHead><section className="wrap changelog"><article><div><span>Coming soon</span><h2>OneBill is getting ready</h2><p>We’re preparing the first public release of OneBill.</p></div><ul><li>The release notes will be published here when the Android app is available.</li></ul></article></section></>}
function About(){return <><PageHead eyebrow="About OneBill" title={<>A simpler way to handle <em>everyday billing.</em></>}>OneBill is a simple billing application designed to help businesses manage their everyday billing, customers and payments with less complexity.</PageHead><section className="wrap about-card"><div><span>Our approach</span><h2>Focused on the essentials.</h2></div><p>OneBill is an independent product designed around clarity, practical organization and a dependable everyday experience. It keeps the focus on the work that matters to your business.</p></section><CTA/></>}
const legal={privacy:['Information collected','How information is used','Data storage','Cloud synchronization','Account information','Customer and business data','Security','Third-party services','Data retention','Your choices','Contact'],terms:['Acceptance of terms','Using OneBill','User responsibilities','Account responsibility','Data responsibility','Intellectual property','Availability','Limitation of liability','Changes to these terms','Contact']};
function Legal({kind}){let title=kind==='privacy'?'Privacy policy':'Terms of use';let isPrivacy=kind==='privacy';let copy=isPrivacy?{intro:'OneBill stores business information on the device and uses account-based cloud services for supported synchronization. This page describes the product approach in plain language.',sections:[['Information collected','OneBill may store account details, business profiles, customers, invoices, payments, income, expenses and related records that you enter into the app.'],['How information is used','The information is used to provide the billing, customer, income, expense and synchronization features of OneBill.'],['Data storage and synchronization','Business data is stored locally so the app remains usable offline. When you are signed in and connectivity is available, supported records synchronize with your account.'],['Security and account information','OneBill uses account authentication and app security options such as App Lock where enabled. Keep your account credentials and device secure.'],['Your choices','You can manage the business information you enter in the app. Business deletion is permanent and removes its local records and associated cloud sync records.'],['Updates and contact','This policy may be updated as OneBill develops. Official support contact details will be published with the public release.']]}:{intro:'These terms describe use of the OneBill Android application for managing business billing and related records.',sections:[['Using OneBill','Use OneBill for your own business administration and keep the information you enter accurate.'],['Your data and account','You are responsible for your account credentials and for the business, customer, invoice, payment, income and expense information entered into your account.'],['Availability','OneBill is designed to keep local business data available offline. Cloud synchronization depends on account access and available connectivity.'],['Business deletion','Deleting a business permanently removes its invoices, customers, inventory, expenses and cloud sync records.'],['Changes to these terms','These terms may be updated as the product and its distribution evolve. The current version will be published here.'],['Contact','Official support contact details will be published with the public release.']]};return <><PageHead eyebrow="Legal" title={title}>{copy.intro}</PageHead><article className="wrap legal">{copy.sections.map(([x,p])=><section key={x}><h2>{x}</h2><p>{p}</p></section>)}</article></>}
function Contact(){return <><PageHead eyebrow="Contact" title={<>Contact <em>OneBill.</em></>}>Have a question, issue, or suggestion? Official support contact details will be published with the public release.</PageHead><section className="wrap contact-card"><span className="feature-symbol">OB</span><h2>OneBill support is coming soon.</h2><p>We’re preparing the official support channel for questions about the Android app, billing, customers, payments and business data.</p></section></>}
function App(){const path=location.pathname.replace(/\/$/,'')||'/';const pages={'/':<Home/>,'/features':<Features/>,'/download':<Download/>,'/whats-new':<WhatsNew/>,'/help':<Help/>,'/about':<About/>,'/privacy':<Legal kind="privacy"/>,'/terms':<Legal kind="terms"/>,'/contact':<Contact/>};useEffect(()=>{window.scrollTo(0,0);document.title=path==='/'?'OneBill — Simple billing for your business':`OneBill — ${path.slice(1).replace('-', ' ')}`},[path]);return <><Navbar/><main>{pages[path]||<Home/>}</main><Footer/></>}
createRoot(document.getElementById('root')).render(<App/>);
